### ISSUE TITLE
 EDD()->session->get( 's3_file_name' ) no longer returning file name in Upload form

### ISSUE THREAD

**Issue by d9media** [easydigitaldownloads/edd-amazon-s3#99] opened 2018-02-21 10:37 UTC
After uploading a file to S3, there is the success message with a "Use file now" link which used to populate the matching input file in the EDD Download settings. It doesn't work anymore. The file name is not being transferred to that input field anymore.

WP 4.9.4

### Begin System Info ###

-- Site Info

Site URL:                 https://site.xyz
Home URL:                 https://site.xyz
Multisite:                No

-- Hosting Provider

Host:                     DBH: localhost:3306, SRV: site.xyz

-- User Browser

Platform:                 Windows 
Browser Name:             Chrome  
Browser Version:          64.0.3282.140 
User Agent String:        Mozilla/5.0 (Windows NT 10.0; Wi 
			  n64; x64) AppleWebKit/537.36 (KH
                          TML, like Gecko) Chrome/64.0.328
                          2.140 Safari/537.36 OPR/51.0.283
                          0.34
                          
-- WordPress Configuration

Version:                  4.9.4
Language:                 en_US
Permalink Structure:      /%postname%/
Active Theme:             Marketify audio))me 1.0
Parent Theme:             Marketify 2.14.2
Show On Front:            page
Page On Front:            Sound Branding For Champions!   From €19 (#26)
Page For Posts:           Unset
ABSPATH:                  /var/www/vhosts/xxx/site.xyz/
Remote Post:              wp_remote_post() works
Table Prefix:             Length: 9   Status: Acceptable
WP_DEBUG:                 Enabled
Memory Limit:             40M
Registered Post Stati:    publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, abandoned, processing, active, inactive

-- EDD Configuration

Version:                  2.8.18
Upgraded From:            None
Test Mode:                Enabled
AJAX:                     Enabled
Guest Checkout:           Enabled
Symlinks:                 Disabled
Download Method:          Direct
Currency Code:            EUR
Currency Position:        after
Decimal Separator:        .
Thousands Separator:      ,
Upgrades Completed:       upgrade_payment_taxes,upgrade_customer_payments_association,upgrade_user_api_keys,remove_refunded_sale_logs,aa_v1_reorganize_customer_meta,stripe_customer_id_migration,upgrade_mailchimp_api3,upgrade_mailchimp_api3_default_list
Download Link Expiration:  hour(s)

-- EDD Page Configuration

Checkout:                 Valid
Checkout Page:            https://site.xyz/checkout/
Success Page:             https://site.xyz/success/
Failure Page:             https://site.xyz/failure/
Downloads Slug:           /cuts

-- EDD Gateway Configuration

Enabled Gateways:         PayPal Standard, Test-Zahlung
Default Gateway:          PayPal Standard

-- EDD Tax Configuration

Taxes:                    Enabled
Tax Rate:                 19
Display On Checkout:      Displayed
Prices Include Tax:       Yes
Country / State Rates:    
                          Country: DE, State: , Rate: 19

-- Must-Use Plugins

AudioMe Optimizations: 1.0

-- WordPress Active Plugins

Admin Color Schemes: 2.2
Admin Columns: 3.1.3
BackWPup: 3.4.4
Easy Digital Downloads: 2.8.18
Easy Digital Downloads - Advanced Sequential Order Numbers: 1.0.8
Easy Digital Downloads - Albums: 1.0.0
Easy Digital Downloads - All Access: 1.0.9
Easy Digital Downloads - Amazon S3: 2.3.8
Easy Digital Downloads - Audiome Customizations: 1.0
Easy Digital Downloads - Cross-sell & Upsell: 1.1.7
Easy Digital Downloads - Downloads As Services: 1.0.6
Easy Digital Downloads - Featured Downloads: 1.0.3
Easy Digital Downloads - Free Downloads: 2.2.7
Easy Digital Downloads - German Market (Alpha): 0.1.0
Easy Digital Downloads - MailChimp: 3.0.3
Easy Digital Downloads - PDF Invoices: 2.2.21
Easy Digital Downloads - Terms Per Product: 1.0.6
Easy Digital Downloads - Variable Defaults: 1.1.0
Easy Digital Downloads - Variable Pricing Features: 1.0.0
EDD Variable Pricing Descriptions: 1.0.3
Force Regenerate Thumbnails: 2.0.6
If Menu: 0.7.1 (needs update - 0.8.2)
Minify HTML: 1.98
Multiple Post Thumbnails: 1.6.6
Pods - Custom Content Types and Fields: 2.7.1
Polylang: 2.3.1
Search & Filter: 1.2.9
User Role Editor: 4.40
WaveSurfer-WP: 2.7.5

-- WordPress Inactive Plugins

Amazon Web Services: 1.0.4 (needs update - 1.0.5)
BulkPress: 0.3.5
Easy Digital Downloads - Stripe Payment Gateway: 2.6.9
qTranslate-X: 3.4.6.8
Taxonomy Images: 0.9.6
W3 Total Cache: 0.9.5.4 (needs update - 0.9.6)

-- Webserver Configuration

PHP Version:              7.1.14
MySQL Version:            5.5.56
Webserver Info:           Apache

-- PHP Configuration

Memory Limit:             1500M
Upload Max Size:          768M
Post Max Size:            1152M
Upload Max Filesize:      768M
Time Limit:               90
Max Input Vars:           10000
Display Errors:           On (1)
PHP Arg Separator:        &

-- PHP Extensions

cURL:                     Supported
fsockopen:                Supported
SOAP Client:              Installed
Suhosin:                  Not Installed

-- Session Configuration

EDD Use Sessions:         Enabled
Session:                  Disabled

### End System Info ###

**Comment by d9media** [comment] 2018-02-21 12:18
It seems

`echo EDD()->session->get( 's3_file_name' ) `

does not return anything.  here is what the script looks like:.

`
			jQuery( document ).ready( function( $ ) {
				$( '.edd-s3-insert' ).click( function() {
					var file = "";
					var bucket = "";
					$( parent.window.edd_filename ).val( file );
					$( parent.window.edd_fileurl ).val( bucket + '/' + file );
					parent.window.tb_remove();
				} );
				console.log("file: ");
			} );
		`

**Comment by d9media** [comment] 2018-02-22 09:48
@pippinsplugins Can you please quickly check what could be the cause? This is breaking the Upload workflow of my client's team so 10 people are waiting for a solution.

Why do you think the object returns an empty string? Checking back with the main uploader, it appears the file land in S3 just fine.

**Comment by mintplugins** [comment] 2018-03-06 05:00
I just replicated this. It only happens for newly uploaded files. Previously uploaded files work correctly. I haven't been able to pinpoint the cause yet.

**Comment by mintplugins** [comment] 2018-03-06 05:02
https://secure.helpscout.net/conversation/534034935/77351/

**Comment by SDavisMedia** [comment] 2018-03-06 08:37
Replicated. This breaks with EDD 2.8.18 only. 2.8.17 and before are working properly.

**Comment by SDavisMedia** [comment] 2018-03-06 10:07
**The PR above does not fully resolve the issue.** I just wanted to get the ball rolling as this is a pretty big deal.

This recent EDD core edit is the culprit: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/master/includes/class-edd-session.php#L364-#L372

All I did here was let S3 start the session. However, if this is even the correct approach, we need to only start the session for this specific scenario. Otherwise we're right back where we started, as this will break the EDD issue again. We'd need to start the session specifically for this S3 functionality to run.

So this is a start, even if we go in another direction.

**Comment by SDavisMedia** [comment] 2018-03-06 10:16
That's a better start, actually. With this approach, the EDD core issue is still fixed and S3 works as well. I still think it's way too general, though.

**Comment by mintplugins** [comment] 2018-03-06 14:28
Confirmed fixed on `issue/99`. Awesome work @SDavisMedia. I haven't had a chance to look at the PR code yet - but it's working 👍

**Comment by pippinsplugins** [comment] 2018-03-06 14:40
Nice going tracking that down!

I don't think this is quite the right approach though as it just undoes the core change, which was important.

I think we can resolve this instead by detecting when we are on a post edit screen. If on the edit or add new screen, allow the session to be started.

**Comment by pippinsplugins** [comment] 2018-03-06 15:00
Spent a bit of time playing with this and found a new solution that doesn't rely on sessions at all.

Using sessions really wasn't necessary and was only used because that was the best I managed to figure out when I originally wrote this. Better method is to pass the file name and bucket through the request parameters, therefor removing the reliance on sessions.

See https://github.com/easydigitaldownloads/edd-amazon-s3/pull/102

**Comment by mintplugins** [comment] 2018-03-06 15:08
pulling and testing real quick

**Comment by mintplugins** [comment] 2018-03-06 15:10
Working here on `issue/99-2`! 👍

**Comment by pippinsplugins** [comment] 2018-03-06 15:12
Great!

@SDavisMedia please package up and release this.

**Closed** 2018-03-06 15:14 UTC
Labels: Bug, Has PR, Needs Testing, Urgent

**Comment by d9media** [comment] 2018-03-08 12:07
Thanks guys. Tested and confirmed! :)
