### ISSUE TITLE
Add option to set Content-Type

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-amazon-s3#52] opened 2017-07-07 17:35 UTC
If you want files to automatically download from Amazon's servers, you can manually set the content-type of each file to be a zip. we have documentation on that here:
http://docs.easydigitaldownloads.com/article/1172-how-do-i-force-files-to-download-in-amazon-s3

A customer has asked whether it would be possible for us to set that content-type automatically when the file is put to AmazonS3. 

This is a note to look into it and see if it is possible. If so, it could be good to add an option which allows the site owner to override the content types of all uploaded files before sending them to Amazon. This would prevent the site-owner from having to log into amazon and manually set the content-type of each file.

**Comment by sunnyratilal** [comment] 2017-07-30 13:46
Closing as this is a duplicate of #27

**Closed** 2017-07-30 13:46 UTC
