### ISSUE TITLE
File uploads in FES

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-amazon-s3#31] opened 2016-06-21 18:35 UTC
At this time, the S3 extension works with FES but only applies to the Downloads Prices and Files field in the submission form. I think enough customers are requesting that S3 support extend, at least optionally, to other file upload fields. Here are the options I see:

A. Add an option in the File Upload field settings for putting the files on S3 instead of local
B. Create a new S3 Upload field which will exist in the Add Extension Created Fields section of the submission form builder
C. Create a new extension which does one of the following if this isn't deemed appropriate for inclusion in the S3 extension
D. If we really can't support anything else, at least write up a little more of an explanation in our docs or in a canned reply explaining why as it isn't clear to customers why only one field is supported

For reference, here's a screenshot of the submission form:
![screenshot 2016-06-21 14 27 42](https://cloud.githubusercontent.com/assets/4993131/16241698/e97c70ac-37bc-11e6-8d48-29d9547c97c4.png)

**Comment by pippinsplugins** [comment] 2016-06-22 02:56
I vote we either add an option to the field or we just upload all files.

**Comment by sunnyratilal** [comment] 2017-09-04 19:17
I've played around with this today and adding this as a separate field within FES is quite complicated because we need to make a custom `wp.media` view with only the `Upload to S3` available.

Using the WP Media API doesn't allow me to force this behaviour directly from the JavaScript, we need to alter filters and actions too.  The problem with this is that it will break the WordPress media manager when used with other fields (i.e. file upload or download files).

I'm thinking adding an option to the `File Upload` field is the best way forward as of now.

**Comment by sunnyratilal** [comment] 2017-09-04 19:36
Hmm, actually, on second thoughts, going to try again, an idea just sprung to mind... ;)

**Comment by zeromajstor** [comment] 2017-09-10 09:23
Is it possible to make for example if using FES you have 2 fields to upload mp3 and wav, to make that mp3 field/file is stored on local server and wav on amazon s3 since its larger size, and that mp3 field is also used for audio preview file, so vendors dont have to upload it twice same thing?

**Comment by sunnyratilal** [comment] 2017-09-18 08:33
Ready for testing!

**Comment by pippinsplugins** [comment] 2017-09-20 13:49
<img width="322" alt="screen shot 2017-09-20 at 8 49 16 am" src="https://user-images.githubusercontent.com/1034109/30647190-99637dbe-9de0-11e7-8656-b2957f0deac4.png">

We'll need to change the text or increase the button size.

**Comment by pippinsplugins** [comment] 2017-09-20 13:52
I'm seeing a couple of PHP notices after putting  the Amazon S3 Upload field on the form:

PHP Notice: Uninitialized string offset: 0 in /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-amazon-s3/includes/class-fes-field.php on line 257
Stack trace:
1. {main}() /Users/pippinwilliamson/Sites/edd/index.php:0
2. require() /Users/pippinwilliamson/Sites/edd/index.php:17
3. require_once() /Users/pippinwilliamson/Sites/edd/wp-blog-header.php:19
4. include() /Users/pippinwilliamson/Sites/edd/wp-includes/template-loader.php:74
5. get_template_part() /Users/pippinwilliamson/Sites/edd/wp-content/themes/vendd/fes_templates/fes-dashboard.php:15
6. locate_template() /Users/pippinwilliamson/Sites/edd/wp-includes/general-template.php:167
7. load_template() /Users/pippinwilliamson/Sites/edd/wp-includes/template.php:647
8. require() /Users/pippinwilliamson/Sites/edd/wp-includes/template.php:690
9. the_content() /Users/pippinwilliamson/Sites/edd/wp-content/themes/vendd/content/content-fes-dashboard.php:28
10. apply_filters() /Users/pippinwilliamson/Sites/edd/wp-includes/post-template.php:240
11. WP_Hook->apply_filters() /Users/pippinwilliamson/Sites/edd/wp-includes/plugin.php:203
12. do_shortcode() /Users/pippinwilliamson/Sites/edd/wp-includes/class-wp-hook.php:298
13. preg_replace_callback() /Users/pippinwilliamson/Sites/edd/wp-includes/shortcodes.php:223
14. do_shortcode_tag() /Users/pippinwilliamson/Sites/edd/wp-includes/shortcodes.php:223
15. FES_Dashboard->display_fes_dashboard() /Users/pippinwilliamson/Sites/edd/wp-includes/shortcodes.php:345
16. FES_Templates->fes_get_template_part() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/classes/frontend/class-dashboard.php:194
17. FES_Templates->fes_locate_template() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/classes/frontend/class-templates.php:112
18. load_template() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/classes/frontend/class-templates.php:161
19. require() /Users/pippinwilliamson/Sites/edd/wp-includes/template.php:690
20. FES_Forms->render_submission_form() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/templates/frontend-edit-product.php:2
21. FES_Form->render_form_frontend() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/classes/frontend/class-forms.php:379
22. EDD_Amazon_S3_FES_Field->render_field_frontend() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/classes/abstracts/class-form.php:261

PHP Warning: Illegal string offset 'file' in /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-amazon-s3/includes/class-fes-field.php on line 257
Stack trace:
1. {main}() /Users/pippinwilliamson/Sites/edd/index.php:0
2. require() /Users/pippinwilliamson/Sites/edd/index.php:17
3. require_once() /Users/pippinwilliamson/Sites/edd/wp-blog-header.php:19
4. include() /Users/pippinwilliamson/Sites/edd/wp-includes/template-loader.php:74
5. get_template_part() /Users/pippinwilliamson/Sites/edd/wp-content/themes/vendd/fes_templates/fes-dashboard.php:15
6. locate_template() /Users/pippinwilliamson/Sites/edd/wp-includes/general-template.php:167
7. load_template() /Users/pippinwilliamson/Sites/edd/wp-includes/template.php:647
8. require() /Users/pippinwilliamson/Sites/edd/wp-includes/template.php:690
9. the_content() /Users/pippinwilliamson/Sites/edd/wp-content/themes/vendd/content/content-fes-dashboard.php:28
10. apply_filters() /Users/pippinwilliamson/Sites/edd/wp-includes/post-template.php:240
11. WP_Hook->apply_filters() /Users/pippinwilliamson/Sites/edd/wp-includes/plugin.php:203
12. do_shortcode() /Users/pippinwilliamson/Sites/edd/wp-includes/class-wp-hook.php:298
13. preg_replace_callback() /Users/pippinwilliamson/Sites/edd/wp-includes/shortcodes.php:223
14. do_shortcode_tag() /Users/pippinwilliamson/Sites/edd/wp-includes/shortcodes.php:223
15. FES_Dashboard->display_fes_dashboard() /Users/pippinwilliamson/Sites/edd/wp-includes/shortcodes.php:345
16. FES_Templates->fes_get_template_part() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/classes/frontend/class-dashboard.php:194
17. FES_Templates->fes_locate_template() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/classes/frontend/class-templates.php:112
18. load_template() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/classes/frontend/class-templates.php:161
19. require() /Users/pippinwilliamson/Sites/edd/wp-includes/template.php:690
20. FES_Forms->render_submission_form() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/templates/frontend-edit-product.php:2
21. FES_Form->render_form_frontend() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/classes/frontend/class-forms.php:379
22. EDD_Amazon_S3_FES_Field->render_field_frontend() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/classes/abstracts/class-form.php:261

Sep 20, 13:50:31
PHP Notice: Uninitialized string offset: 0 in /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-amazon-s3/includes/class-fes-field.php on line 257
Stack trace:
1. {main}() /Users/pippinwilliamson/Sites/edd/index.php:0
2. require() /Users/pippinwilliamson/Sites/edd/index.php:17
3. require_once() /Users/pippinwilliamson/Sites/edd/wp-blog-header.php:19
4. include() /Users/pippinwilliamson/Sites/edd/wp-includes/template-loader.php:74
5. get_template_part() /Users/pippinwilliamson/Sites/edd/wp-content/themes/vendd/fes_templates/fes-dashboard.php:15
6. locate_template() /Users/pippinwilliamson/Sites/edd/wp-includes/general-template.php:167
7. load_template() /Users/pippinwilliamson/Sites/edd/wp-includes/template.php:647
8. require() /Users/pippinwilliamson/Sites/edd/wp-includes/template.php:690
9. the_content() /Users/pippinwilliamson/Sites/edd/wp-content/themes/vendd/content/content-fes-dashboard.php:28
10. apply_filters() /Users/pippinwilliamson/Sites/edd/wp-includes/post-template.php:240
11. WP_Hook->apply_filters() /Users/pippinwilliamson/Sites/edd/wp-includes/plugin.php:203
12. do_shortcode() /Users/pippinwilliamson/Sites/edd/wp-includes/class-wp-hook.php:298
13. preg_replace_callback() /Users/pippinwilliamson/Sites/edd/wp-includes/shortcodes.php:223
14. do_shortcode_tag() /Users/pippinwilliamson/Sites/edd/wp-includes/shortcodes.php:223
15. FES_Dashboard->display_fes_dashboard() /Users/pippinwilliamson/Sites/edd/wp-includes/shortcodes.php:345
16. FES_Templates->fes_get_template_part() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/classes/frontend/class-dashboard.php:194
17. FES_Templates->fes_locate_template() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/classes/frontend/class-templates.php:112
18. load_template() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/classes/frontend/class-templates.php:161
19. require() /Users/pippinwilliamson/Sites/edd/wp-includes/template.php:690
20. FES_Forms->render_submission_form() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/templates/frontend-edit-product.php:2
21. FES_Form->render_form_frontend() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/classes/frontend/class-forms.php:379
22. EDD_Amazon_S3_FES_Field->render_field_frontend() /Users/pippinwilliamson/Sites/edd/wp-content/plugins/edd-fes/classes/abstracts/class-form.php:261

I think they are due to not having any file saved yet.

@sunnyratilal Would it be possible to add the file type option like the regular File Upload field has?

**Comment by sunnyratilal** [comment] 2017-09-21 08:08
@pippinsplugins The errors have been resolved and I've added the file type option too.

**Comment by pippinsplugins** [comment] 2017-09-21 20:20
@sunnyratilal there's a JS error that pops up as soon as you click into the file extensions field now:

Uncaught TypeError: Cannot read property 'length' of undefined
https://edd.com/vendd/wp-content/plugins/easy-digital-downloads/assets/js/admin-scripts.js?ver=2.8.5 line 1289

**Comment by sunnyratilal** [comment] 2017-09-22 16:01
@pippinsplugins This is a bug in FES. The same error is also caused by the `File Upload` field.

**Comment by sunnyratilal** [comment] 2017-09-22 16:01
@pippinsplugins It's an odd bug though - when initially adding the field to the form, no errors are shown. They only display once you save the form and click into the field extensions field row.

**Comment by sunnyratilal** [comment] 2017-09-22 16:04
@pippinsplugins Scratch that, it's a bug in EDD core. Getting the same errors in the console when creating a new discount code and clicking into the `Download Requirements` field.

**Comment by sunnyratilal** [comment] 2017-09-25 15:31
Issue opened in EDD core at https://github.com/easydigitaldownloads/easy-digital-downloads/issues/6023

**Comment by sunnyratilal** [comment] 2017-09-25 15:31
@pippinsplugins as this is a Core bug, can this be merged in the interim?

**Comment by pippinsplugins** [comment] 2017-09-25 15:59
@sunnyratilal could you get a PR submitted to core so that we can use that to fully verify it's not a problem here?

**Comment by sunnyratilal** [comment] 2017-09-25 16:40
@pippinsplugins the error should have disappeared now. It was a missing `data-` attribute. I'll still submit a PR to core for anywhere else where the attribute is missing.

**Comment by brashrebel** [comment] 2017-09-26 20:12
Just tested and everything worked beautifully with no errors. Added field to submission form, uploaded a file as a vendor, tested file extension validation, all good.

**Comment by sunnyratilal** [comment] 2017-09-26 20:13
Thanks @brashrebel!

**Closed** 2017-09-26 20:13 UTC
Labels: Enhancement, Has PR, Needs Testing
